name: another_flutter_usb_write
description: Write raw data to USB device on Android. Fell Free to colaborate, every PR is welcome!
version: 1.0.1
homepage: https://github.com/lcsvcn/another_flutter_usb_write

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.1
  mockito: ^5.3.2
  async: ^2.9.0

  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: hr.integrator.flutter_usb_write
        pluginClass: FlutterUsbWritePlugin
